### ISSUE TITLE
Remove jQuery/moment dependency

### ISSUE THREAD

**Issue by ocombe** [swimlane/ng2d3#10]
A few files use jquery/moment functions/helpers, we have to remove these

**Comment by marjan-georgiev** [comment]
jQuery is removed. We are going to keep moment for the time being. It's useful for parsing and formatting dates.

**Comment by ocombe** [comment]
true, just check if there isn't what you need in D3 itself: https://github.com/d3/d3-time-format

**Comment by ajackson-cpi** [comment]
What's the status of removing Moment? It's important for keeping builds small. 
Is is possible to indicate which codepaths it's needed, so we can avoid those?

**Comment by amcdnl** [comment]
@marjan-georgiev - what do we use moment for?
