### ISSUE TITLE
Curve property breaks and blocks rendering of chart

### ISSUE THREAD

**Issue by tadmore** [swimlane/ng2d3#100]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

When using the `curve` property for an area-chart or line-chart, the chart fails to render and the browser console throws an error stating: 
```
error_handler.js:47 EXCEPTION: Error in ./LineChart class LineChart - inline template:45:14 caused by: curve is not a function
error_handler.js:49 ORIGINAL EXCEPTION: curve is not a function  
error_handler.js:53 TypeError: curve is not a function
    at line (line.js:21)
    at LineSeries.update (ng2d3.js:8487)
    at LineSeries.ngOnChanges (ng2d3.js:8462)
    at _View_LineChart3.detectChangesInternal (LineChart.ngfactory.js:934)
    at _View_LineChart3.AppView.detectChanges (view.js:271)
    at _View_LineChart3.DebugAppView.detectChanges (view.js:376)
    at _View_LineChart0.AppView.detectContentChildrenChanges (view.js:289)
    at _View_LineChart0.detectChangesInternal (LineChart.ngfactory.js:470)
    at _View_LineChart0.AppView.detectChanges (view.js:271)
    at _View_LineChart0.DebugAppView.detectChanges (view.js:376)
```

**Expected behavior**

The chart should render using the d3-shape defined by the `curve` property (like: Cardinal, Linear, etc...)  

**Reproduction of the problem**

1. Load a <line-chart> component and apply a standard set of properties (I'm using the one's from the documentation.  Apply a value for the `curve` var to pass to the <line-chart> in the component's .ts 

```
curve = 'Cardinal';
```

2. Add the `[curve]` property like so:
```
<line-chart
            [view]="areaview"
            [scheme]="colorScheme"
            [results]="clientdata"
            [gradient]="gradient"
            [xAxis]="showXAxis"
            [yAxis]="showYAxis"
            [legend]="showLegend"
            [showXAxisLabel]="showXAxisLabel"
            [showYAxisLabel]="showYAxisLabel"
            [xAxisLabel]="xAxisLabel"
            [yAxisLabel]="yAxisLabel"
            [curve]="curve"
            [autoScale]="autoScale"
            (clickHandler)="clickHandler($event)">
          </line-chart>
```

**What is the motivation / use case for changing the behavior?**

Trying to load a customized chart using Angular2 and d3 where the lines are curved instead of straight.

**Please tell us about your environment:**

- macOS El Capitan
- node v6.7.0
- npm v 3.10.3
- webpack
- angular 2
- angular cli v1.0.0-beta.17

* **ng2d3 version:** 1.6.2

Yes 

* **Angular version:** 2.0.2

Yes 

* **Browser:** [Chrome 54.0.2840.98 ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
The curve input accepts a function, not a string.

Use `d3.shape.curveCardinal` instead

**Comment by amcdnl** [comment]
Lets make sure this is in the docs

**Comment by Prasannavk94** [comment]
I am having the same problem . @marjan-georgiev Please provide a documentation on how to use d3 curves.
