### ISSUE TITLE
Error integration with Ionic2

### ISSUE THREAD

**Issue by zeornelas** [swimlane/ng2d3#101]
I am using ng2d3 with ionic2. It works very well when we compile it locally, but if I make a build for Android it retrieves the following error:

> [16:36:11]  copy finished in 110 ms
[16:36:13]  Error: Unexpected value 'NG2D3Module' imported by the module 'AppModule'
[16:36:13]  ngc failed
[16:36:13]  ionic-app-script task: "build"
[16:36:13]  Error: Error

I am using the following config:

```
{
  "name": "ionic-prototype",
  "author": "blabla",
  "homepage": "http://www.blabla.com/",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },
  "dependencies": {
    "@angular/common": "^2.2.3",
    "@angular/compiler": "^2.2.3",
    "@angular/compiler-cli": "^2.2.3",
    "@angular/core": "^2.2.3",
    "@angular/forms": "^2.2.3",
    "@angular/http": "^2.2.3",
    "@angular/platform-browser": "^2.2.3",
    "@angular/platform-browser-dynamic": "^2.2.3",
    "@angular/platform-server": "^2.2.3",
    "@ionic/storage": "1.1.6",
    "d3": "^4.4.0",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "^2.2.7",
    "ionicons": "3.0.0",
    "lodash": "^4.16.6",
    "moment": "^2.17.0",
    "ng2d3": "^1.6.2",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.46",
    "typescript": "^2.1.1"
  },
  "description": "ionic-prototype: An Ionic project",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": []
}

```

**Comment by zeornelas** [comment]
@amcdnl I started studying why we have this error.  I started experimenting a solution to the problem, I don't know much about the compile process.. I think we need a metadata.json that is needed for the AOT compiler. I tried to compile the project and it generated a ng2d3.metadata.json. When we import the module it points to the release folder, so I copied the file from the dist folder to the release folder.  The error is now a little bit different:

`[14:33:33]  Error: Can't export value CommonModule from NG2D3Module as it was neither declared nor imported!
[14:33:33]  ngc failed
[14:33:33]  ionic-app-script task: "build"
[14:33:33]  Error: Error`

**Comment by amcdnl** [comment]
Give it another shot, i just switched this up and it should be there in 1.7 - https://github.com/swimlane/ng2d3/blob/master/release/ng2d3.module.metadata.json

**Comment by zeornelas** [comment]
It is not working @amcdnl . I have created a new project just to test it. You can produce it doing the following:
Node version: v6.9.1
NPM version: 3.10.8

```
npm install -g ionic cordova
ionic start helloWorld --v2
cd helloWorld
npm install --save ng2d3 moment d3 (is it possible to include moment and d3 in ng2d3 package?)
```

src\app\app.module.ts:
```

import { NgModule } from '@angular/core';
import { IonicApp, IonicModule } from 'ionic-angular';
import { MyApp } from './app.component';
import { AboutPage } from '../pages/about/about';
import { ContactPage } from '../pages/contact/contact';
import { HomePage } from '../pages/home/home';
import { TabsPage } from '../pages/tabs/tabs';
import {BrowserModule} from '@angular/platform-browser'
import {NG2D3Module} from 'ng2d3';


@NgModule({
  declarations: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  imports: [
    NG2D3Module,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  providers: []
})
export class AppModule {}

```


src\pages\about\about.html:
```
<ion-header>
  <ion-navbar>
    <ion-title>
      About
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <bar-vertical
      [view]="view"
      [scheme]="colorScheme"
      [results]="single"
      [gradient]="gradient"
      [xAxis]="showXAxis"
      (clickHandler)="clickHandler($event)">
    </bar-vertical>

</ion-content>
```

src\pages\about\about.ts
```
import { Component } from '@angular/core';

import { NavController } from 'ionic-angular';
import {single} from './data';



@Component({
  selector: 'page-about',
  templateUrl: 'about.html'
})
export class AboutPage {

  single: any[];
  // multi: any[];

  view: any[] = [300, 100];

  // options
  showXAxis = true;
  showYAxis = true;
  gradient = false;
  showLegend = false;
  showXAxisLabel = false;
  xAxisLabel = 'Country';
  showYAxisLabel = true;
  yAxisLabel = 'Population';

  colorScheme = {
    domain: ['#5AA454', '#A10A28', '#C7B42C', '#AAAAAA']
  };

  // pie
  showLabels = true;
  explodeSlices = false;
  doughnut = false;

  // line, area
  autoScale = true;

  constructor(public navCtrl: NavController) {
    Object.assign(this, {single})
  }

}
```

src\pages\about\data.ts
```
export var single = [
  {
    "name": "Germany",
    "value": 8940000
  },
  {
    "name": "USA",
    "value": 5000000
  },
  {
    "name": "France",
    "value": 7200000
  }
];
```

If I run `ionic serve` it will render the bar-chart correctly in the About page. But if I try:
```
ionic platform add android
ionic build android
```

It returns the following:
```
[11:49:03]  ionic-app-scripts 0.0.45
[11:49:03]  build prod started ...
[11:49:03]  clean started ...
[11:49:03]  clean finished in 3 ms
[11:49:03]  copy started ...
[11:49:03]  ngc started ...
[11:49:03]  copy finished in 54 ms
[11:49:19]  Error: Error at
            <MYPROJECTPATH>/.tmp/node_modules/ng2d3/release/common/tooltip/tooltip.component.ngfac
tory.ts:305:45
[11:49:19]  Property 'title' does not exist on type 'TooltipContentComponent'.
[11:49:19]  Error at
            <MYPROJECTPATH>/.tmp/node_modules/ng2d3/release/common/tooltip/tooltip.component.ngfac
tory.ts:308:40
[11:49:19]  Property 'title' does not exist on type 'TooltipContentComponent'.
[11:49:19]  Error at
            <MYPROJECTPATH>/.tmp/node_modules/ng2d3/release/common/scale-legend.component.ngfactor
y.ts:72:7
[11:49:19]  Supplied parameters do not match any signature of call target.
[11:49:19]  Error at
            <MYPROJECTPATH>/.tmp/node_modules/ng2d3/release/common/legend.component.ngfactory.ts:8
5:7
[11:49:19]  Supplied parameters do not match any signature of call target.
[11:49:19]  Error at
            <MYPROJECTPATH>/.tmp/node_modules/ng2d3/release/common/charts/chart.component.ngfactor
y.ts:108:7
[11:49:19]  Supplied parameters do not match any signature of call target.
[11:49:19]  Error at
            <MYPROJECTPATH>/.tmp/node_modules/ng2d3/release/common/svg-linear-gradient.component.n
gfactory.ts:81:7
[11:49:19]  Supplied parameters do not match any signature of call target.
[11:49:19]  Error at
            <MYPROJECTPATH>/.tmp/node_modules/ng2d3/release/bar-chart/bar.component.ngfactory.ts:1
38:9
[11:49:19]  Supplied parameters do not match any signature of call target.
[11:49:19]  Error at
            <MYPROJECTPATH>/.tmp/node_modules/ng2d3/release/bar-chart/bar-vertical.component.ngfac
tory.ts:176:7
[11:49:19]  Supplied parameters do not match any signature of call target.
[11:49:19]  Error at
            <MYPROJECTPATH>/.tmp/node_modules/ng2d3/release/bar-chart/bar-vertical.component.ngfac
tory.ts:396:23
[11:49:19]  Module ''*'' has no exported member 'Wrapper_XAxis'.
[11:49:19]  Error at
            <MYPROJECTPATH>/.tmp/node_modules/ng2d3/release/bar-chart/bar-vertical.component.ngfac
tory.ts:450:23
[11:49:19]  Module ''*'' has no exported member 'Wrapper_YAxis'.
[11:49:19]  Error at <MYPROJECTPATH>/.tmp/pages/about/about.ngfactory.ts:252:42
[11:49:19]  Property 'clickHandler' does not exist on type 'AboutPage'.
[11:49:19]  ngc failed
[11:49:19]  ionic-app-script task: "build"
[11:49:19]  Error: Error
```

**Comment by zeornelas** [comment]
Hi @amcdnl . Any news on this? I want to help, can you point me where to start?

**Comment by nicholas-richardson** [comment]
I am receiving the same errors.

`[16:39:34]  ionic-app-scripts 0.0.45
[16:39:34]  build prod started ...
[16:39:34]  clean started ...
[16:39:34]  clean finished in 4 ms
[16:39:34]  copy started ...
[16:39:34]  ngc started ...
[16:39:34]  copy finished in 332 ms
[16:40:01]  Error: Error at
            C:/Users/nicjr/Documents/Personal/Hydrate.Me-0.0.3/.tmp/node_modules/ng2d3/release/common/tooltip/tooltip.component.ngfactory.ts:305:45
[16:40:01]  Property 'title' does not exist on type 'TooltipContentComponent'.
[16:40:01]  Error at
            C:/Users/nicjr/Documents/Personal/Hydrate.Me-0.0.3/.tmp/node_modules/ng2d3/release/common/tooltip/tooltip.component.ngfactory.ts:308:40
[16:40:01]  Property 'title' does not exist on type 'TooltipContentComponent'.
[16:40:01]  Error at
            C:/Users/nicjr/Documents/Personal/Hydrate.Me-0.0.3/.tmp/node_modules/ng2d3/release/common/scale-legend.component.ngfactory.ts:72:7
[16:40:01]  Supplied parameters do not match any signature of call target.
[16:40:01]  Error at
            C:/Users/nicjr/Documents/Personal/Hydrate.Me-0.0.3/.tmp/node_modules/ng2d3/release/common/legend.component.ngfactory.ts:85:7
[16:40:01]  Supplied parameters do not match any signature of call target.
[16:40:01]  Error at
            C:/Users/nicjr/Documents/Personal/Hydrate.Me-0.0.3/.tmp/node_modules/ng2d3/release/common/charts/chart.component.ngfactory.ts:108:7
[16:40:01]  Supplied parameters do not match any signature of call target.
[16:40:01]  Error at
            C:/Users/nicjr/Documents/Personal/Hydrate.Me-0.0.3/.tmp/node_modules/ng2d3/release/common/svg-linear-gradient.component.ngfactory.ts:81:7
[16:40:01]  Supplied parameters do not match any signature of call target.
[16:40:01]  Error at
            C:/Users/nicjr/Documents/Personal/Hydrate.Me-0.0.3/.tmp/node_modules/ng2d3/release/common/svg-radial-gradient.component.ngfactory.ts:71:7
[16:40:01]  Supplied parameters do not match any signature of call target.
[16:40:01]  Error at
            C:/Users/nicjr/Documents/Personal/Hydrate.Me-0.0.3/.tmp/node_modules/ng2d3/release/pie-chart/pie-arc.component.ngfactory.ts:169:7
[16:40:01]  Supplied parameters do not match any signature of call target.
[16:40:01]  Error at
            C:/Users/nicjr/Documents/Personal/Hydrate.Me-0.0.3/.tmp/node_modules/ng2d3/release/gauge/gauge.component.ngfactory.ts:148:7
[16:40:01]  Supplied parameters do not match any signature of call target.
[16:40:01]  Error at
            C:/Users/nicjr/Documents/Personal/Hydrate.Me-0.0.3/.tmp/node_modules/ng2d3/release/gauge/gauge.component.ngfactory.ts:379:40
[16:40:01]  Property 'legend' does not exist on type 'Gauge'.
[16:40:01]  Error at
            C:/Users/nicjr/Documents/Personal/Hydrate.Me-0.0.3/.tmp/components/water-gauge/water-gauge.ngfactory.ts:127:42
[16:40:01]  Property 'clickHandler' does not exist on type 'WaterGaugeComponent'.
[16:40:01]  ngc failed
[16:40:01]  ionic-app-script task: "build"
[16:40:01]  Error: Error
`


Environment Information:
`{
  "name": "Hydrate.Me",
  "author": "Nicholas Richardson",
  "homepage": "https://www.nicholas_richardson.com",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "core-js": "^2.4.1",
    "d3": "^4.3.0",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "moment": "^2.17.0",
    "ng2d3": "^1.6.2",
    "rxjs": "^5.0.0-rc.3",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.45",
    "typescript": "2.0.6"
  },
  "description": "Hydrate.Me3: A simple app to help you monitor your water intake.",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard",
    "cordova-plugin-inappbrowser"
  ],
  "cordovaPlatforms": []
}
`

Other Info:
` ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.0.0
Xcode version: Not installed
`

**Comment by amcdnl** [comment]
These are AoT related, please try 1.8.1

**Comment by nicholas-richardson** [comment]
Using 1.81 fixed my problems! Thank you. For others using Ionic 2 I was able to get everything working properly under the following environment.

```
{
  "name": "Hydrate.Me",
  "author": "Nicholas Richardson",
  "homepage": "https://www.nicholas_richardson.com",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "core-js": "^2.4.1",
    "d3": "^4.3.0",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "moment": "^2.17.0",
    "ng2d3": "1.8.1",
    "rxjs": "^5.0.0-rc.3",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.45",
    "typescript": "2.0.6"
  },
  "description": "Hydrate.Me3: A simple app to help you monitor your water intake.",
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard",
    "cordova-plugin-inappbrowser"
  ],
  "cordovaPlatforms": []
}
```

**Comment by amcdnl** [comment]
W00t!

**Comment by zeornelas** [comment]
@nicholas-richardson  Can you post  your last config?

I have an error related with the Observable. I have already updated from Node 6 to 7, and tried the config you posted earlier.

```
Error
Close
Runtime Error
Error in ./AboutPage class AboutPage - caused by: Observable_1.Observable.fromEvent is not a function
Stack
TypeError: Observable_1.Observable.fromEvent is not a function
    at eval (<MYPROJECTPATH>\node_modules\ng2d3\release\index.js:6544:50)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:13422)
    at Object.onInvoke (<MYPROJECTPATH>\node_modules\@angular\core\src\zone\ng_zone.js:238:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:13373)
    at e.run (http://localhost:8100/build/polyfills.js:3:10809)
    at NgZone.run (<MYPROJECTPATH>\node_modules\@angular\core\src\zone\ng_zone.js:128:62)
    at BarVerticalComponent.BaseChartComponent.bindWindowResizeEvent (<MYPROJECTPATH>\node_modules\ng2d3\release\index.js:6543:19)
    at BarVerticalComponent.BaseChartComponent.bindResizeEvents (<MYPROJECTPATH>\node_modules\ng2d3\release\index.js:6506:14)
    at BarVerticalComponent.ngAfterViewInit (<MYPROJECTPATH>\node_modules\ng2d3\release\index.js:4769:14)
    at _View_AboutPage0.detectChangesInternal (/AppModule/AboutPage/component.ngfactory.js:170:80)
Ionic Framework: 2.0.0-rc.3
Ionic Native: 2.2.3
Ionic App Scripts: 0.0.45
Angular Core: 2.1.1
Angular Compiler CLI: 2.1.1
Node: 7.2.0
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
```

**Comment by amcdnl** [comment]
that is dupe of this - https://github.com/swimlane/ng2d3/issues/119 ... see notes there

**Comment by zeornelas** [comment]
@amcdnl Your last fix works when I do ionic serve, there is no more the Observable error. But when I build on Android I still have this errors:
```
[14:35:38]  Error: Error at
            <MYPROJECTPATH>/.tmp/node_modules/ng2d3/release/bar-chart/bar-vertical.component.ngfactory.ts:226:32
[14:35:38]  Module ''*'' has no exported member 'Wrapper_ChartComponent'.
[14:35:38]  Error at
           <MYPROJECTPATH>/.tmp/node_modules/ng2d3/release/bar-chart/bar-vertical.component.ngfactory.ts:396:32
[14:35:38]  Module ''*'' has no exported member 'Wrapper_XAxisComponent'.
[14:35:38]  Error at
            <MYPROJECTPATH>/.tmp/node_modules/ng2d3/release/bar-chart/bar-vertical.component.ngfactory.ts:450:32
[14:35:38]  Module ''*'' has no exported member 'Wrapper_YAxisComponent'.
[14:35:38]  ngc failed
[14:35:38]  ionic-app-script task: "build"
[14:35:38]  Error: Error
```

**Comment by nicholas-richardson** [comment]
@amcdnl I am experience the same issue as @zeornelas when building. Ionic serve is working as expected.

Error:
