### ISSUE TITLE
Multi-color gradients

### ISSUE THREAD

**Issue by amcdnl** [swimlane/ng2d3#102]
Extend gradients to support a coloration based on the ordinal or the value.

Example API:
`colorScaleType: linear|ordinal`

This enables this type of accenting on line charts, where the taller the line the more it changes colors.

![img](https://d13yacurqjgara.cloudfront.net/users/13307/screenshots/1728095/line_chart_1x.jpg)

**Comment by marjan-georgiev** [comment]
Done in 3.0.0 branch.
