### ISSUE TITLE
Example Webpack Application

### ISSUE THREAD

**Issue by jhuntoo** [swimlane/ng2d3#111]
Hi, this library looks great and I really wanted to kick the tyres, but getting it to work with my webpack build has proven a challenge. I'm not sure if anyone here has experience of _consuming_ this library with webpack, but here's what I have tried already, and I always get this error in the browser `Uncaught ReferenceError: d3 is not defined`

Do you know of any example repo that uses webpack ?

Sorry I'm wary that I haven't supplied, a minimal repro here...

Here's what i've tried

``` console
npm i d3
npm i ng2d3
```

``` typescript
// vendor.ts
import 'd3';
import 'ng2d3/release/index.js';
import 'ng2d3/release/ng2d3.css';
```
``` json
// webpack.config
{
resolve: {
      alias: {
        'd3': helpers.root('node_modules/d3/index.js')
      },
}
}
```

**Comment by marjan-georgiev** [comment]
This is a d3 question more than an ng2d3 one.

Try `import * as d3 from 'd3';` instead.

Here's an example of an angular CLI app using ng2d3 running on webpack.

https://github.com/marjan-georgiev/Angular-CLI-NG2D3-Demo

**Comment by jhuntoo** [comment]
@marjan-georgiev Thanks for the quick reply, the issue was in fact due to my unnecessary fiddling with webpack `external` libraries.

So in short, the npm install and vendor.ts steps from above should be enough.

This would be useful to have on the main README.md IMO,  so that folks passing by can instantly see how to install it.

Some other things that I think should be mentioned as well, is that d3 needs to be included in your bundle, and perhaps something about only including the sub modules to encourage smaller bundle size (I haven't actually tested that yet, but I'm assuming it works).

I realise that some of this may be obvious for some, but these little things really do help with providing a good OOTB experience for more people.

Happy to help with docs PR if you agree.

**Comment by marjan-georgiev** [comment]
Any help with the docs and guides is highly appreciated.

We don't bundle d3 together with ng2d3 in order to keep the file size small, which is why it is a peer dependency.

Also, we don't import all d3 modules. You can see which ones are used here:
https://github.com/swimlane/ng2d3/blob/master/src/d3.ts
