### ISSUE TITLE
Discrete Bar chat using ng2d3

### ISSUE THREAD

**Issue by gopinathshiva** [swimlane/ng2d3#113]
**I'm submitting a ...**  (check one with "x")

[ ] feature request

**Current behavior**
I am new to angular 2 and d3, I find ng2d3 useful to my project. But I found discrete bar chart missing in the example

**Expected behavior**
Expecting discrete bar chart feature in ng2d3 if unavailable

If discrete bar chart could be drawn using ng2d3, could you please provide me an example of the same. I believe that would be helpful to many in future. Appreciate the support given

**Comment by marjan-georgiev** [comment]
What do you mean by "Discrete" bar chart? Any examples?

We support several types of bar charts, you can see all of them on the demo page:
https://swimlane.github.io/ng2d3/

**Comment by gopinathshiva** [comment]
You can view here http://krispo.github.io/ng2-nvd3/ . You can select discreteBarChart value in the dropdown to show the chart

**Comment by marjan-georgiev** [comment]
Yes, the vertical and horizontal bar charts support that.

**Comment by gopinathshiva** [comment]
Appreciate that. Just now checked the demo and changed the data. Its working. Closing the issue
