### ISSUE TITLE
Line chart doesn't support real time data.

### ISSUE THREAD

**Issue by rockers7414** [swimlane/ng2d3#118]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
The line chart doesn't support the real-time feature.

**Expected behavior**
The line chart supports the real-time feature.

**Please tell us about your environment:**
OS X 10.12.1

* **ng2d3 version:** 
1.7.3

* **Angular version:**
2.1.0

* **Browser:** 
chrome

* **Language:** 
Typescript 2.0.3

**Comment by rockers7414** [comment]
I thought the problem is the update function doesn't update the series data and didn't trigger the ngOnChange?

**Comment by marjan-georgiev** [comment]
The data you pass to the chart needs to be immutable. Have you tried that?

**Comment by rockers7414** [comment]
No, I didn't try it. I'll try it tomorrow. Thanks. :)

**Comment by frosenberg** [comment]
Did you ever solve that? Is there an example?

**Comment by marjan-georgiev** [comment]
This is not a bug. All charts support real time data.  t is just not shown on the demo page for the line and area charts.

**Comment by frosenberg** [comment]
Well, I cannot get it to work. I keep updating the array with data from a websocket but the charts does not draw it.

**Comment by marjan-georgiev** [comment]
As stated above, the data must be immutable.

Try this:
```data = [...data]``` 

to generate a new data array from the existing one. This will make the component register the change and trigger update.

**Comment by frosenberg** [comment]
That works. Does this have any performance implications? I'm expecting lots of data points. 

I'll report back if I find any but maybe you have done some experiments already.

**Comment by marjan-georgiev** [comment]
This was done specifically for performance. If we wanted to get change detection to work with mutable objects, we would have to compare the data on every cycle, which is super expensive. With immutable data, we need to only compare the reference.

Read more: 
http://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html
http://blog.angular-university.io/how-does-angular-2-change-detection-really-work/

**Comment by frosenberg** [comment]
Great. Thanks for the links. I'm pretty new to Ng2

**Comment by amcdnl** [comment]
@marjan-georgiev - we should add a post in docs about this...

**Comment by ptrblgh** [comment]
Related to real time data, I have created a plunkr:
[https://plnkr.co/edit/Nij7gO4jgqdN2mNPIFJp](https://plnkr.co/edit/Nij7gO4jgqdN2mNPIFJp)

My problem is that the memory consumption of browser grows with time. Even though I slice the results array.

Any suggestions pls? :)

**Comment by aleho70** [comment]
I have same problem with memory consumption and stack exhausing in version 7.3.0, I found that one of the reason was number-card, but there is problem also with other chars.

**Comment by virtuotechnologies** [comment]
This link will help you:
https://stackoverflow.com/questions/46033540/ngx-charts-render-dynamic-data

**Comment by utkarshmankad** [comment]
> This was done specifically for performance. If we wanted to get change detection to work with mutable objects, we would have to compare the data on every cycle, which is super expensive. With immutable data, we need to only compare the reference.
> 
> Read more:
> http://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html
> http://blog.angular-university.io/how-does-angular-2-change-detection-really-work/

I have made it to work on single array data. But unable to implement the same for series data - [{ name: .... , series : [{ name: ....., value: ....}, { name: ....., value: .....}]. I have tried to implement arr = [...arr] over series array, but it doesn't seem to work. Can you please help me out on this? Thanks.
