### ISSUE TITLE
"rxjs" and "index.map" in deployed "index.js" and "index.min.js"

### ISSUE THREAD

**Issue by alanpurple** [swimlane/ng2d3#123]
current version: 1.8.2

"rxjs" should be "rxjs/Rx"

index.map should be index.js.map

in index.min.js,  mapping file should be index.min.js.map, it's written as "index.js.map" currently

**Comment by amcdnl** [comment]
Fixed rx.

index.min.js.map is there, see-> https://github.com/swimlane/ng2d3/blob/master/release/index.min.js.map

**Comment by alanpurple** [comment]
@amcdnl  no, i mean in original files, map file names are wrong
