### ISSUE TITLE
getting following error after importing ng2d3 module

### ISSUE THREAD

**Issue by skbelalmd** [swimlane/ng2d3#124]
ERROR in ./~/ng2d3/release/index.js
Module not found: Error: Can't resolve 'd3-array' in 'E:\dlProjects\tap-in-new-ui\node_modules\ng2d3\release'
 @ ./~/ng2d3/release/index.js 8:119-138
 @ ./src/app/energy-data/energy-data.module.ts
 @ ./src/app/layout/layout.routes.ts
 @ ./src/app/layout/layout.module.ts
 @ ./src/app/app.routes.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/ng2d3/release/index.js
Module not found: Error: Can't resolve 'd3-brush' in 'E:\dlProjects\tap-in-new-ui\node_modules\ng2d3\release'
 @ ./~/ng2d3/release/index.js 8:140-159
 @ ./src/app/energy-data/energy-data.module.ts
 @ ./src/app/layout/layout.routes.ts
 @ ./src/app/layout/layout.module.ts
 @ ./src/app/app.routes.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/ng2d3/release/index.js
Module not found: Error: Can't resolve 'd3-color' in 'E:\dlProjects\tap-in-new-ui\node_modules\ng2d3\release'
 @ ./~/ng2d3/release/index.js 8:161-180
 @ ./src/app/energy-data/energy-data.module.ts
 @ ./src/app/layout/layout.routes.ts
 @ ./src/app/layout/layout.module.ts
 @ ./src/app/app.routes.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/ng2d3/release/index.js
Module not found: Error: Can't resolve 'd3-force' in 'E:\dlProjects\tap-in-new-ui\node_modules\ng2d3\release'
 @ ./~/ng2d3/release/index.js 8:182-201
 @ ./src/app/energy-data/energy-data.module.ts
 @ ./src/app/layout/layout.routes.ts
 @ ./src/app/layout/layout.module.ts
 @ ./src/app/app.routes.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/ng2d3/release/index.js
Module not found: Error: Can't resolve 'd3-format' in 'E:\dlProjects\tap-in-new-ui\node_modules\ng2d3\release'
 @ ./~/ng2d3/release/index.js 8:203-223
 @ ./src/app/energy-data/energy-data.module.ts
 @ ./src/app/layout/layout.routes.ts
 @ ./src/app/layout/layout.module.ts
 @ ./src/app/app.routes.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/ng2d3/release/index.js
Module not found: Error: Can't resolve 'd3-hierarchy' in 'E:\dlProjects\tap-in-new-ui\node_modules\ng2d3\release'
 @ ./~/ng2d3/release/index.js 8:225-248
 @ ./src/app/energy-data/energy-data.module.ts
 @ ./src/app/layout/layout.routes.ts
 @ ./src/app/layout/layout.module.ts
 @ ./src/app/app.routes.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/ng2d3/release/index.js
Module not found: Error: Can't resolve 'd3-interpolate' in 'E:\dlProjects\tap-in-new-ui\node_modules\ng2d3\release'
 @ ./~/ng2d3/release/index.js 8:250-275
 @ ./src/app/energy-data/energy-data.module.ts
 @ ./src/app/layout/layout.routes.ts
 @ ./src/app/layout/layout.module.ts
 @ ./src/app/app.routes.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/ng2d3/release/index.js
Module not found: Error: Can't resolve 'd3-scale' in 'E:\dlProjects\tap-in-new-ui\node_modules\ng2d3\release'
 @ ./~/ng2d3/release/index.js 8:277-296
 @ ./src/app/energy-data/energy-data.module.ts
 @ ./src/app/layout/layout.routes.ts
 @ ./src/app/layout/layout.module.ts
 @ ./src/app/app.routes.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/ng2d3/release/index.js
Module not found: Error: Can't resolve 'd3-selection' in 'E:\dlProjects\tap-in-new-ui\node_modules\ng2d3\release'
 @ ./~/ng2d3/release/index.js 8:298-321
 @ ./src/app/energy-data/energy-data.module.ts
 @ ./src/app/layout/layout.routes.ts
 @ ./src/app/layout/layout.module.ts
 @ ./src/app/app.routes.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

ERROR in ./~/ng2d3/release/index.js
Module not found: Error: Can't resolve 'd3-shape' in 'E:\dlProjects\tap-in-new-ui\node_modules\ng2d3\release'
 @ ./~/ng2d3/release/index.js 8:323-342
 @ ./src/app/energy-data/energy-data.module.ts
 @ ./src/app/layout/layout.routes.ts
 @ ./src/app/layout/layout.module.ts
 @ ./src/app/app.routes.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
 @ multi main

**Comment by amcdnl** [comment]
Please provide info requested in the template. This information gives me no useful details to even start to help you. I'm closing this until we get more info and/or a demo of this.

**Comment by skbelalmd** [comment]
I have resolved this one.  But there is another issue/bug with bar chart.
Have a look at http://tapin.azurewebsites.net/#/app/tables/issue 

View the page in chrome and edge browsers.

In edge, the bars are visible, but the color is nor rendered. But in chrome, the bars are not visible.
The code and data is copied from the examples provided.
