### ISSUE TITLE
clickHandler does not seem to trigger on bar-horizontal

### ISSUE THREAD

**Issue by vladimir-ivanov** [swimlane/ng2d3#143]
https://plnkr.co/edit/tczlGeJYacaKwBvEkRaq?p=preview

clickHandler does not trigger when clicking on a bar

**Comment by vladimir-ivanov** [comment]
aha, got it, you have renamed it to select - might be useful to update the examples :-)

**Comment by bomberblue07** [comment]
Seriously y'all. The docs are woefully out of date.
