### ISSUE TITLE
Demo broken with official angular 2 release

### ISSUE THREAD

**Issue by sgruhier** [swimlane/ng2d3#33]
It's easy to fix but I cannot as it's on plunker

**Comment by qazqwezxc** [comment]
What's the issue that needs to be fixed? I'm new and curious to the development of Angular 2.

**Comment by sgruhier** [comment]
I think you just need to change 
```
    <script src="https://npmcdn.com/zone.js@0.6.12/dist/zone.js"></script>
```
to 
```
    <script src="https://npmcdn.com/zone.js@0.6.23/dist/zone.js"></script>
```
it did it on this one
https://plnkr.co/edit/V3Z1gNH96edqiXr2lxKy?p=preview

**Comment by juristr** [comment]
@sgruhier @qazqwezxc Hi, thx for reporting. We're going to fix this soon. I'll let you know

**Comment by marjan-georgiev** [comment]
Updated the demos.
