### ISSUE TITLE
Uncaught ReferenceError: __decorate is not defined

### ISSUE THREAD

**Issue by david-bulte** [swimlane/ng2d3#34]
Trying to use ng2d3 with the angular2-FINAL release. I'm also using the latest angular-cli (beta-14), using webpack.

After "npm installing" the following d3 libraries (d3-array d3-brush d3-color d3-format d3-interpolate d3-scale d3-selection d3-shape), I managed to compile my project. However when I load my webapp, I get the following exception:

> chart.component.js:32 Uncaught ReferenceError: __decorate is not defined

Anything else I should install?

**Comment by david-bulte** [comment]
Note that I do **not** have that exception if I import NG2D3Module from the **src dir** ("ng2d3/src/ng2d3") iso the release dir ("ng2d3/release/ng2d3"). 

(I do see some errors like

> c:\system9\sourcesWEB\MYNEXUZ\MyNexuz\node_modules\ng2d3\src\bar-chart\bar-horizontal-2d.component.ts:154:20 
> Property 'includes' does not exist on type 'any[]'.
> 

but that's not related i guess)

**Comment by amcdnl** [comment]
@ocombe its probably because `ts-helpers` aren't included in the build. Thoughts on best approach?

**Comment by sgruhier** [comment]
I had the same issue, an found on google that adding
```
 		"lib": ["dom"]
```
to compilerOptions in tsconfig.json fixed that __decorate issue

**Comment by amcdnl** [comment]
@sgruhier - can u confirm if this still occurs in latest?
