### ISSUE TITLE
can not use this module into shared module

### ISSUE THREAD

**Issue by vivdkool** [swimlane/ng2d3#36]
We can not use this module in to shared module since common module use browser module can we fix this please?
basically lazy loaded module

**Comment by ocombe** [comment]
What error do you get ?

**Comment by vivdkool** [comment]
it says you can not import browser module twice you should use common module instead, I clone that project and changes bowser module to common module and in axismodule too.. and it works in my project.

I have one another question the pie chart doesn't look awesome it doesn't have tooltip option how can i customize that... ?

**Comment by marjan-georgiev** [comment]
> I have one another question the pie chart doesn't look awesome it doesn't have tooltip option how can i customize that... ?

Tooltips are coming in the next version. You won't have to change anything in your code. They will just appear.

**Comment by vivdkool** [comment]
how easy to look and feel even i render in angular 2 material it come out i have to do that and explode also not working...

**Comment by marjan-georgiev** [comment]
@vivdkool Could you provide a plunkr where we can see your configuration with the errors, please?

**Comment by vivdkool** [comment]
@marjan-georgiev i have changed some code and its woking fine with lazy loaded module would like to see my code..

**Comment by marjan-georgiev** [comment]
In that case I'm closing this issue.

**Comment by Bsujeet** [comment]
i would like see how you have resolved the issue.
Thanks
