### ISSUE TITLE
Not AoT Compatible

### ISSUE THREAD

**Issue by isaacplmann** [swimlane/ng2d3#39]
I'm planning to use this library, and I noticed that it isn't AoT compatible yet.

I've written [an article](https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.sansddmdl) that walks through generating `*.metadata.json` files for your library and troubleshooting errors that might come up.  I'll work on a PR if I get a chance.

**Comment by amcdnl** [comment]
@isaacplmann - Ya, we have some dependencies on d3 doing some HTML manipulation around animations and other stuff. We are slowly removing them but have some dependencies on Angular2's limited dynamic animation variables. Any help would be very welcome!

**Comment by isaacplmann** [comment]
Using D3 for DOM manipulation might block universal (not an expert there), but I don't think it has any effect on AoT.
