### ISSUE TITLE
only works with cjs

### ISSUE THREAD

**Issue by alanpurple** [swimlane/ng2d3#40]
umd format not working

with systemjs

only ng2d3.cjs.js 
and ng2d3.umd.js with ( format:'cjs' ) works

angular version: 2.1.0.beta.0

**Comment by amcdnl** [comment]
Please give more information and I'll be happy to investigate.

**Comment by alanpurple** [comment]
@amcdnl 
![image](https://cloud.githubusercontent.com/assets/4515120/19333869/1760e5fa-9133-11e6-9d46-3f976f899023.png)

**Comment by alanpurple** [comment]
@amcdnl  with ng2d3.cjs.js, works fine
