### ISSUE TITLE
Add spline interpolation option for lines and areas 

### ISSUE THREAD

**Issue by marjan-georgiev** [swimlane/ng2d3#52]
Add an input property to line and area charts that specifies the interpolation algorithm used to generate the paths. 

The available values would be 'linear', 'cardinal', and 'monotone'.

Example: 
http://bl.ocks.org/mbostock/4342190

**Comment by marjan-georgiev** [comment]
Added an input called `curve` to the line and all area charts. The type is one of d3's curve functions:
https://github.com/d3/d3-shape#curves

```
[curve]="d3.shape.curveLinear"
```

**Comment by dtstsUI** [comment]
hi,

can you provide a working plunker for this.

i found myself struggling with implementing this curve.

thanks a lot.

**Comment by valentinbdv** [comment]
+1 don't understand exactly how to make it work?

I guess we have to put our own curve function or import the d3 library?

Thanks!

**Comment by olliechick** [comment]
See https://github.com/swimlane/ngx-graph/issues/50 for some pointers

**Comment by parthdevloper** [comment]
**I have understood how it works** 💯 

to get Linear type, here is the solution :
component.html
```
<ngx-charts-polar-chart
  [view]="view]"
  [scheme]="colorScheme"
  [results]="_Data"
  [legend]="Legend"
  [xAxis]="XAxis"
  [curve]="linearCurve"
>
</ngx-charts-polar-chart>
```

component.ts

```
import * as shape from 'd3-shape';

  linearCurve= shape.curveLinearClosed;

```

and you will get linear curve.

Hope you find this solution helpful 👍 

Here are different inbuilt functions : 

![image](https://user-images.githubusercontent.com/58413215/89712771-af7e8f80-d9b0-11ea-8455-da1dbe723978.png)


[>>reference<<](https://github.com/swimlane/ngx-charts/blob/master/src/app/app.component.ts)

**Comment by aelbazz** [comment]
> **I have understood how it works** 💯
> 
> to get Linear type, here is the solution : component.html
> 
> ```
> <ngx-charts-polar-chart
>   [view]="view]"
>   [scheme]="colorScheme"
>   [results]="_Data"
>   [legend]="Legend"
>   [xAxis]="XAxis"
>   [curve]="linearCurve"
> >
> </ngx-charts-polar-chart>
> ```
> 
> component.ts
> 
> ```
> import * as shape from 'd3-shape';
> 
>   linearCurve= shape.curveLinearClosed;
> ```
> 
> and you will get linear curve.
> 
> Hope you find this solution helpful 👍
> 
> Here are different inbuilt functions :
> 
> ![image](https://user-images.githubusercontent.com/58413215/89712771-af7e8f80-d9b0-11ea-8455-da1dbe723978.png)
> 
> [>>reference<<](https://github.com/swimlane/ngx-charts/blob/master/src/app/app.component.ts)

thanks
