### ISSUE TITLE
Add event listener to manually trigger update

### ISSUE THREAD

**Issue by marjan-georgiev** [swimlane/ng2d3#58]
After adding chart resize functionality, the charts can now be resized to fit their parent containers when the window is resized. This is done by not specifying the `view` input property of the chart.

However, if the parent container dimensions change without the window being resized, window.resize will not fire and the chart will not be resized.

We need to add an event listener to the charts that can manually trigger update() from outside.

**Comment by amcdnl** [comment]
Not needed anymore w/ CD.

**Comment by dave-null** [comment]
Why is this not needed anymore? Is there a function to call? I have a problem with ngx-charts that would be solved by this: The view-property is not calculating chart sizes correctly, since its parent container seems not to be initialized on calculation.
