### ISSUE TITLE
Force directed graph

### ISSUE THREAD

**Issue by isaacplmann** [swimlane/ng2d3#60]
I'd like to have a force directed graph as part of this library.  I'm working on a PR to add it.

**Comment by marjan-georgiev** [comment]
Great - please make sure to use the existing infrastructure and helper components wherever possible:

- BaseChart
- Chart container
- tooltips and other helpers.

**Comment by isaacplmann** [comment]
Yeah, chart container and tooltips are really useful.  BaseChart’s update function tries to copy the results data, but force directed graphs don’t have a series style data structure.  I’ll have the PR ready today and we can talk more specifics there.
