### ISSUE TITLE
mistyped filename and sourcemapping url

### ISSUE THREAD

**Issue by alanpurple** [swimlane/ng2d3#66]
release/ng2d3.map should be release ng2d3.js.map

at the end of ng2d3.min.js,
sourceMappingURL should be ng2d3.min.js.map, without unnecessary path

**Comment by amcdnl** [comment]
These are auto generated, not sure how this got messed up.

**Comment by marjan-georgiev** [comment]
Updated the source map filename.

**Comment by alanpurple** [comment]
@marjan-georgiev  same in 1.5.2, not solved

**Comment by marjan-georgiev** [comment]
It is solved in master, will be in the next release.

**Comment by alanpurple** [comment]
@marjan-georgiev  ng2d3.min.js still has wrong map filename( v 1.6.0 ).
It should be ng2d3.min.js.map
