### ISSUE TITLE
Customize the legend name max length

### ISSUE THREAD

**Issue by ronydj** [swimlane/ng2d3#68]
Currently the max length is 17 characters for a legend value name.  When a string has more than 17 characters the string is abbreviated with a suspension points at the end.

Ex.

Legend              [original: "Legend with more than 17 characters"]
In the chart is shown as:  "Legend with more..." 

Would be good if we had a way to customize this limit.

**Comment by marjan-georgiev** [comment]
In version 1.5.2 the truncation is controlled via CSS, so the text will always extend to the full width of the legend, and then truncate. This should probably solve your specific use case.

However, we plan to add an input property so the users can override default truncation limit on other parts of the chart (axis tick labels, tooltips).

**Comment by odedOT** [comment]
have you done it?
