### ISSUE TITLE
(1.5.0)animation is too slow for some type

### ISSUE THREAD

**Issue by alanpurple** [swimlane/ng2d3#69]
check  https://swimlane.github.io/ng2d3/ ( e.g., Horizontal bar chart )

**Comment by amcdnl** [comment]
Can you elaborate?

**Comment by alanpurple** [comment]
@amcdnl  Just go to horizontal bar chart, the bar animation is like 10x slower ( like a slow motion video )

my chrome version is 54.0.2840.87 m (64-bit) and my os is windows 10 pro x64

**Comment by amcdnl** [comment]
We made several changes to make text fitting awesome. Will dig in and see what we can do here.

**Comment by marjan-georgiev** [comment]
This is fixed in 1.5.1
