### ISSUE TITLE
Is gitbook page not maintained?

### ISSUE THREAD

**Issue by alanpurple** [swimlane/ng2d3#70]
should I not look that page? the samples aren't working at all

https://swimlane.gitbooks.io/ng2d3/content/charts/bar-vertical.html

**Comment by amcdnl** [comment]
Gitbook is maintained, we are continuing to strive to improve the features and its very difficult to rapidly do that and keep docs perfect. We will investigate and make appropriate changes.

**Comment by marjan-georgiev** [comment]
All gitbook pages have been updated to latest version.
