### ISSUE TITLE
Angular-cli WebpackRequire compile error

### ISSUE THREAD

**Issue by Omotayad** [swimlane/ng2d3#71]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Angular-cli compilation error - 94% asset optimizationError in bail mode: [default] F:\Github\OryxMCIv2\src\ng2d3\node_modules\awesome-typescript-loader\lib\runtime.d.ts:20:12
Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'any', but here has type 'WebpackRequire'.

**Expected behavior**
Build should be successful

**Reproduction of the problem**
Running ng build on angular-cli fails. Project fails to compile

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
win 10 

* **ng2d3 version:1.5.0

* **Angular version:** 2.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
I can not reproduce this on my demo angular-cli project: https://github.com/marjan-georgiev/Angular-CLI-NG2D3-Demo

**Comment by amcdnl** [comment]
@Omotayad - can u make a demo project showing the error?

**Comment by Omotayad** [comment]
Hi Guys,

I finally found traced the problem to a line of code in the typings.d.ts file in my project. I commented out the third line and the issue was fixed. 

declare var System: any;
declare var module: { id: string };
//declare var require: any;

Thanks.
