### ISSUE TITLE
Hover of legend doesn't highlight bar

### ISSUE THREAD

**Issue by amcdnl** [swimlane/ng2d3#73]
When you hover over an entry in the legend, it should highlight the respective svg that corresponds to that value.

Likewise, when you hover a svg in the chart it should highlight the legend entry that corresponds to that value.

**Comment by amcdnl** [comment]
Hovering legend and highlighting the bar/arc/etc is done.

**Comment by marjan-georgiev** [comment]
Fixed in 3.0.0
