### ISSUE TITLE
Multi-series line chart tooltip line disappears when hover inside

### ISSUE THREAD

**Issue by amcdnl** [swimlane/ng2d3#75]
When I have a multi-series line chart and I hover inside the grouped tooltip, the lines and bulbs go away. We should maintain those until focus is left.

![img](http://content.screencast.com/users/amcdaniel22/folders/Snagit/media/292b4429-308e-4fe2-88ac-e6cb1a64df1f/2016-11-18_11-57-17.png)

**Comment by marjan-georgiev** [comment]
This has been fixed.
