### ISSUE TITLE
Show percentages instead of actual values in tooltips on normalized charts

### ISSUE THREAD

**Issue by marjan-georgiev** [swimlane/ng2d3#79]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Normalized bar and area charts are showing actual values in the tooltips instead of percentages.

**Expected behavior**
Normalized bar and area charts should show percentage values.

**Comment by narendra-agashe** [comment]
@marjan-georgiev is it possible to show values instead of percentage on normalized bar chart? at the moment only percentage shows up.

**Comment by marjan-georgiev** [comment]
@narendra-agashe yes, you can pass it a custom tooltipTemplate, but you will need to calculate the values from the percentages yourself.
