### ISSUE TITLE
Linear Gauge Chart

### ISSUE THREAD

**Issue by amcdnl** [swimlane/ng2d3#81]
# Requirement
Linear variation of gauge chart in horizontal and vertical forms.

Design:
![img](http://content.screencast.com/users/amcdaniel22/folders/Snagit/media/99829163-166a-41a5-8b9b-1bd75eaae348/2016-12-15_15-01-22.png)

Examples:
- http://www.infragistics.com/media/442707/linear-orientation.png
- http://www.visifire.com/blog/wp-content/uploads/2012/10/Windows8_Gauge1.jpg

**Comment by marjan-georgiev** [comment]
Added in 3.0.0
