### ISSUE TITLE
Gradient hover on line/area charts

### ISSUE THREAD

**Issue by amcdnl** [swimlane/ng2d3#92]
When hovering a line/area chart, it should apply gradient fill if turned on to the hovered item.

Line Chart Example: http://www.screencast.com/t/Sogam6CXL
Area Chart Example: http://www.screencast.com/t/BW2eD8UiC

**Comment by marjan-georgiev** [comment]
Done.

**Comment by daimz** [comment]
@amcdnl could I ask how you achieved that effect?
